// ***********************************************************************
// Assembly         : RuntimeStuff
// Author           : RS
// Created          : 11-09-2025
//
// Last Modified By : RS
// Last Modified On : 11-18-2025
// ***********************************************************************
// <copyright file="Resources.Designer.cs" company="Rudnev Sergey">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace RuntimeStuff.Properties {
    using System;


    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuntimeStuff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected at least {0} arguments.
        /// </summary>
        /// <value>The action extensions convert action expected at least 0 arguments.</value>
        internal static string ActionExtensions_ConvertAction_Expected_at_least__0__arguments {
            get {
                return ResourceManager.GetString("ActionExtensions_ConvertAction_Expected_at_least__0__arguments", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Item cannot be null.
        /// </summary>
        /// <value>The ex binding ListView add range item cannot be null.</value>
        internal static string EX_BindingListView_AddRange_Item_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("EX_BindingListView_AddRange_Item_Cannot_Be_Null", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Элемент с ключом '{0}' уже существует в кэше..
        /// </summary>
        /// <value>The ex cache key already exists.</value>
        internal static string EX_CACHE_KEY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EX_CACHE_KEY_ALREADY_EXISTS", resourceCulture);
            }
        }
    }
}
