<Project Sdk="Microsoft.NET.Sdk">

	<!-- PreBuild: удаляем старые nupkg -->
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<ItemGroup>
			<NupkgFiles Include="bin\$(Configuration)\*.nupkg" />
		</ItemGroup>
		<Delete Files="@(NupkgFiles)" />
	</Target>

	<!-- Основные свойства проекта -->
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>2026.04.14.1</Version>
		<Authors>Rudnev Sergey</Authors>
		<PackageProjectUrl>https://github.com/Unholius/RuntimeStuff</PackageProjectUrl>
		<PackageDescription>Набор утилит и вспомогательных хелперов общего назначения для .NET проектов: расширения строк, работы с файлами, сериализации, Simple ORM, LINQ-утилиты и др.</PackageDescription>
		<PackageTags>Utilities;Helpers;Extensions;Common;Tools;String;File;Serialization;LINQ</PackageTags>
		<RepositoryUrl>https://github.com/Unholius/RuntimeStuff</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<RootNamespace>System</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<WarningsAsErrors>SA*;CA*;S*</WarningsAsErrors>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
	  <AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
	</ItemGroup>

	<!-- Генерация ресурсов -->

</Project>
